version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    container_name: app-qr-container
    image: app-qr:1.0.0
    depends_on:
      - db
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: division_cuentas_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: examplepassword