apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-helm-chart.fullname" . }}
spec:
  selector:
    app: {{ include "my-helm-chart.fullname" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.service.port }}
  type: ClusterIP
