Vagrant.configure("2") do |config|
  config.vm.define "desafio-m13-it"
  config.vm.box = "ubuntu/focal64"  # Puedes seleccionar otra versión de Ubuntu si lo prefieres.
  config.vm.network "private_network", type: "dhcp"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "6144"
    vb.cpus = 4
  end

  config.vm.provision "shell", path: "provision.sh" # Crearemos este script en el siguiente paso.

end
