apiVersion: v1
kind: Service
metadata:
  name: app-qr-service
  namespace: desafio-final
spec:
  selector:
    app: app-qr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort  # Cambia esto según tus necesidades
