apiVersion: v1
kind: Service
metadata:
  name: app-qr-service
spec:
  selector:
    app: app-qr
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000 # Puerto de la aplicación
  type: ClusterIP
