name: ci

on:
  push:
    branches:
      - "main"
    paths:
      - "App-QR/**"

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: App-QR/Dockerfile


  build:
    runs-on: ubuntu-latest
    needs: hadolint
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Python
        uses: actions/setup-python@v2.3.2
        with:
          python-version: 3.8
      -
        name: Install dependencies
        run: pip install -r App-QR/requirements.txt
      -
        name: Run tests
        run: python App-QR/tests/test_app.py


  push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:App-QR"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app-qr:${{ github.run_number }}