name: ci

on:
  push:
    branches:
      - "main"
    paths:
      - "App-QR/**"

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          context: "{{defaultContext}}:App-QR"
          dockerfile: Dockerfile


  build:
    runs-on: ubuntu-latest
    need: hadolint
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:App-QR"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app-qr:${{ github.run_number }}
